version: "3.9"

services:
  app:
    build: .
    volumes:
      - ./:/var/www
    container_name: lumen-api-app
    networks:
      - lumen-network

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    container_name: lumen-api-nginx
    networks:
      - lumen-network

  database:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./.database/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${DB_PASSWORD:-lumen@123}
      - MYSQL_USERNAME=${DB_USERNAME:-lumen}
      - MYSQL_DATABASE=${DB_DATABASE:-lumen_api}
    container_name: lumen-api-database
    networks:
      - lumen-network

networks:
  lumen-network:
    driver: bridge
